### PR TITLE
Flush::poll_complete calls poll_trailers after EOS data frame

### PR DESCRIPTION
**Pull request by hawkw**
Downstream implementors of the `tower_h2::Body` API (such as Conduit) often use
`Body::poll_trailers` as an indicator that a stream has finished successfully,
regardless of whether the stream was terminated by a TRAILERS frame or a DATA
frame with the END_STREAM bitset. Therefore, it is necessary to ensure that 
`Flush::poll_complete` always calls `poll_trailers` to end a stream, even
when it was ended by a DATA frame.

The original implementation of `Flush::poll_complete` called `poll_body` a
second time after that function returned a DATA frame, which meant that
`poll_trailers` would be called when the DATA frame has the EOS bit set.
However, d9b3140e543af7887893cbf2f4337afd28d15839 changed this function, so
that this was no longer the case. This change means that Conduit's telemetry
code, which uses `poll_trailers` as the indication that an end of stream event
should be recorded, no longer records stream ends when a stream is terminated
by a DATA frame (runconduit/conduit#954). 

This PR changes `tower-h2::Flush` to ensure that `poll_trailers` is called when
a stream is ended by a DATA frame, so the contract is upheld. Since the stream
has already ended, there should not be a TRAILERS frame following the DATA 
frame, so we expect `poll_trailers` to always return `None`; if it returns
`Some`, the TRAILERS frame is ignored and `tower_h2` logs a warning. I 
considered making this a debug assertion, but I thought that since the protocol
violation only results in the erroneous TRAILERS frame being dropped, it was 
probably incorrect to panic here.

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

**Comment by seanmonstar** [comment]
I don't believe this contract is correct. The point of `is_end_stream` is to allow for optimizations, so that we don't have to send empty `DATA` frames, and we don't have to poll again.

I believe anything relying on this "contract" should instead be fixed.

**Comment by hawkw** [comment]
@seanmonstar My original solution to this problem was to change the telemetry code downstream in Conduit so that an end-of-stream event could be generated in `MeasuredBody::poll_data` _or_ `MeasuredBody::poll_trailers` if the stream had ended, which also fixed the issue. However,  @olix0r told me that was incorrect, and that there was a contract that `poll_trailers` is always called. 

I'd be happy to make either change, but perhaps the two of you should clarify which would be correct?

**Comment by olix0r** [comment]
the always-call-poll_trailers contract was a very early assumption when we were working on h2. It makes sense that these assumptions have changed, so we should probably change conduit (as you initially did, @hawkw )

**Comment by hawkw** [comment]
Okay, thanks @olix0r, will do. Given that, I'm going to close this PR for now.

**Pull request closed without merging**
