### PR TITLE
Add `stream_id` accessor to `RecvBody`

### PR DESCRIPTION
**Pull request by hawkw**
This branch adds an accessor for the stream ID to `RecvBody`. It depends on
carllerche/h2#292, and therefore currently overrides the `h2` dependency to
point at that branch. Once that branch is merged, that override will no 
longer be necessary.

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

### CODE REVIEW

**Comment by olix0r** [comment]
Can/Should the stream_id also be exposed on the ResponseFuture?

**Comment by hawkw** [comment]
@olix0r Yeah, good call. I added that in e10c2330e43312e9929b9d1d42214b05623cbf79.

**Comment by carllerche** [comment]
Ideally https://github.com/carllerche/h2/pull/292 can be released to crates.io before merging this. Mostly to avoid downstream crate conflicts.

**Comment by olix0r** [comment]
Is this waiting on an h2 release?

**Comment by seanmonstar** [comment]
@hawkw want to prepare an h2 commit and send a PR? Just follow what the other ones do :D

**Comment by hawkw** [comment]
@seanmonstar Sure, I'd be happy to!

**Comment by hawkw** [comment]
Updated this branch to depend on h2 v0.1.11.

**Comment by olix0r** [comment]
lgtm! i'd like a shipit from @seanmonstar or @carllerche

**Pull request merged**
